export declare const rateLimitError = "Too many requests received from your network, please try again in some time or <a href='https://www.browserstack.com/contact?too_many_requests=true'>contact us</a>";
export declare const EMAIL_VALIDATION_REGEX: RegExp;
export declare const INACTIVITY_TIME_LIMIT = 300000;
export declare const DB_NAME = "BrowserStack";
export declare const schema: {
    deviceLogs: string;
};
export declare const DB_VERSION = 1;
export declare const messages: {
    startRecordingError: string;
    stopRecordingError: string;
    downloadRecordingError: string;
    discardRecordingError: string;
    recordingDownloaded: string;
    recordingDiscarded: string;
};
export declare const storybookCookieId = "userID";
export declare const storyBookSecretKey = "browserstack@storybook";
export declare const ICON_TOKENS: {
    'neutral-weak': string;
    'neutral-default': string;
    'neutral-strong': string;
    'neutral-weakest': string;
    'neutral-weaker': string;
    'neutral-strongest': string;
    'neutral-inverse-default': string;
    'neutral-inverse-weaker': string;
    'attention-weaker': string;
    'attention-weak': string;
    'attention-default': string;
    'attention-strong': string;
    'attention-stronger': string;
    'attention-strongest': string;
    'attention-inverse-default': string;
    'brand-weakest': string;
    'brand-weaker': string;
    'brand-weak': string;
    'brand-default': string;
    'brand-strong': string;
    'brand-stronger': string;
    'danger-weakest': string;
    'danger-weaker': string;
    'danger-weak': string;
    'danger-default': string;
    'danger-strong': string;
    'danger-stronger': string;
    'success-weakest': string;
    'success-weaker': string;
    'success-weak': string;
    'success-default': string;
    'success-strong': string;
    'success-stronger': string;
    'sky-400': string;
    'sky-600': string;
};
export declare const SURFACE_TOKENS: {
    default: string;
    strong: string;
};
export declare const TEXT_TOKENS: {
    transparent: string;
    current: string;
    white: string;
    black: string;
    base: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    brand: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    danger: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    success: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    attention: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    info: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    pink: {
        100: string;
        300: string;
        700: string;
        800: string;
        950: string;
    };
    'neutral-weakest': string;
    'neutral-weaker': string;
    'neutral-weak': string;
    'neutral-default': string;
    'neutral-inverse-default': string;
    'neutral-inverse-weak': string;
    'neutral-inverse-weakest': string;
    'attention-weaker': string;
    'attention-weak': string;
    'attention-default': string;
    'attention-strong': string;
    'attention-stronger': string;
    'attention-inverse-default': string;
    'brand-weaker': string;
    'brand-weak': string;
    'brand-default': string;
    'brand-strong': string;
    'brand-stronger': string;
    'brand-strongest': string;
    'danger-weaker': string;
    'danger-weak': string;
    'danger-default': string;
    'danger-strong': string;
    'danger-stronger': string;
    'danger-strongest': string;
    'success-weaker': string;
    'success-weak': string;
    'success-default': string;
    'success-strong': string;
    'success-stronger': string;
};
export declare const BG_TOKENS: {
    transparent: string;
    current: string;
    white: string;
    black: string;
    base: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    brand: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    danger: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    success: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    attention: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    info: {
        50: string;
        100: string;
        200: string;
        300: string;
        400: string;
        500: string;
        600: string;
        700: string;
        800: string;
        900: string;
    };
    pink: {
        100: string;
        300: string;
        700: string;
        800: string;
        950: string;
    };
    'neutral-default': string;
    'neutral-strong': string;
    'neutral-stronger': string;
    'neutral-strongest': string;
    'neutral-inverse-weakest': string;
    'neutral-inverse-weaker': string;
    'neutral-inverse-weak': string;
    'neutral-inverse-default': string;
    'neutral-default-hover': string;
    'neutral-default-disabled': string;
    'neutral-stronger-hover': string;
    'neutral-stronger-disabled': string;
    'neutral-strongest-hover': string;
    'neutral-strongest-disabled': string;
    'neutral-strong-hover': string;
    'neutral-inverse-weaker-hover': string;
    'attention-weakest': string;
    'attention-weaker': string;
    'attention-weak': string;
    'attention-default': string;
    'attention-stronger': string;
    'attention-weaker-disabled': string;
    'attention-weaker-hover': string;
    'attention-weak-disabled': string;
    'attention-weak-hover': string;
    'attention-weakest-hover': string;
    'brand-weakest': string;
    'brand-weaker': string;
    'brand-weak': string;
    'brand-default': string;
    'brand-stronger': string;
    'brand-weaker-disabled': string;
    'brand-weaker-hover': string;
    'brand-default-hover': string;
    'brand-default-disabled': string;
    'brand-weakest-hover': string;
    'danger-weakest': string;
    'danger-weaker': string;
    'danger-default': string;
    'danger-stronger': string;
    'danger-default-hover': string;
    'danger-default-disabled': string;
    'danger-weaker-hover': string;
    'danger-weaker-disabled': string;
    'danger-weakest-hover': string;
    'success-weakest': string;
    'success-weaker': string;
    'success-default': string;
    'success-strong': string;
    'success-stronger': string;
    'success-weaker-hover': string;
    'success-weaker-disabled': string;
    'success-default-hover': string;
    'success-default-disabled': string;
    'success-weakest-hover': string;
    'success-strong-hover': string;
    'success-strong-disabled': string;
    'input-default': string;
    'input-default-hover': string;
    'input-default-disabled': string;
    'raised-default': string;
    'raised-default-hover': string;
};
